import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'Latest Projects',
  projects: [
    {
      id: getId(),
      name: 'BlockchainCap',
      url: '',
      repo: '',
      img: '/fyp.png',
      year: 2024,
      tags: ['NextJs', 'TailwindCSS', 'Blockchain'],
    },

{
      id: getId(),
      name: 'SkillSync',
      url: 'https://profile-sable-nu.vercel.app/',
      repo: '',
      img: '/profile.png',
      year: 2024,
      tags: ['NextJs', 'GitHubAPI', 'MongoDB'],
    },

{
      id: getId(),
      name: 'FAQ Genie',
      url: 'https://faq-genie.vercel.app/',
      repo: 'https://github.com/Ahsankhalid618/FaqGenie',
      img: '/FaqGenie.png',
      year: 2024,
      tags: ['NextJs', 'TailwindCSS', 'Gemini-flash'],
    },
{
      id: getId(),
      name: 'EDS Solutions',
      url: 'https://next-landing-page-seven-alpha.vercel.app/',
      repo: 'https://github.com/Ahsankhalid618/Next-landingPage',
      img: '/eds.png',
      year: 2024,
      tags: ['NextJs', 'Framer', 'shadCN'],
    },
{
      id: getId(),
      name: 'Chat App',
      url: 'https://ahsankhalid618.github.io/chatapp/',
      repo: 'https://github.com/Ahsankhalid618/chatapp',
      img: '/ChatApp.png',
      year: 2023,
      tags: ['React', 'Firebase'],
    },
{
      id: getId(),
      name: 'RealEstate Pakistan',
      url: 'https://real-estate-pakistan.vercel.app/',
      repo: 'https://github.com/Ahsankhalid618/RealEstate-Pakistan',
      img: '/RealEstate.png',
      year: 2024,
      tags: ['ReactJs', 'MUI'],
    },
{
      id: getId(),
      name: 'News App',
      url: 'https://ahsankhalid618.github.io/News-website/',
      repo: 'https://github.com/Ahsankhalid618/News-website',
      img: '/NewsWebsite.png',
      year: 2023,
      tags: ['React', 'Bootstrap5'],
    },
{
      id: getId(),
      name: 'NextCent',
      url: 'https://bytewise-vite-projectpages.vercel.app/',
      repo: 'https://github.com/Ahsankhalid618/bytewise-vite-project',
      img: '/Nexcent.png',
      year: 2024,
      tags: ['ReactJs', 'TailwindCSS'],
    },
{
      id: getId(),
      name: 'Weather App',
      url: 'https://ahsankhalid618.github.io/react-weather-app/',
      repo: 'https://github.com/Ahsankhalid618/react-weather-app',
      img: '/Weather.png',
      year: 2023,
      tags: ['React', 'OpenWeatherMap API'],
    },
{
      id: getId(),
      name: 'Bytewise Learning',
      url: 'https://bytewise-bootstrap-project.netlify.app/',
      repo: 'https://github.com/Ahsankhalid618/Bytewise-bootstrap-project',
      img: '/BytewiseLearning.png',
      year: 2024,
      tags: ['bootstrap5', 'CSS3'],
    },
{
      id: getId(),
      name: 'Portfolio Website',
      url: '',
      repo: '',
      img: '/portfolio.png',
      year: 2023,
      tags: ['NextJs', 'TypeScript', 'TailwindCSS'],
    },
   {
      id: getId(),
      name: 'Word Counter',
      url: 'https://ahsankhalid618.github.io/wordcounter/',
      repo: 'https://github.com/Ahsankhalid618/wordcounter',
      img: '/WordCounter.png',
      year: 2022,
      tags: ['React', 'Bootstrap5'],
    },
    {
      id: getId(),
      name: 'Netflix Clone',
      url: 'https://github.com/Ahsankhalid618/netflix-clone',
      repo: 'https://github.com/Ahsankhalid618/netflix-clone',
      img: '/neflx.png',
      year: 2022,
      tags: ['React', 'CSS3'],
    },
    {
      id: getId(),
      name: 'Code Editor',
      url: 'https://ahsankhalid618.github.io/react_code_editor/',
      repo: 'https://github.com/Ahsankhalid618/react_code_editor',
      img: '/code.png',
      year: 2023,
      tags: ['React', 'Sass', 'TailwindCSS'],
    },

  ],
};
